# Generated by Django 4.2.4 on 2023-08-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_review_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="have_review",
            field=models.BooleanField(default=False),
        ),
    ]
